### ISSUE TITLE
请问这个项目训练的时候没有验证的过程么

### ISSUE THREAD

**Issue by clw5180** [heshuting555/NAIC_Person_ReID_DMT#4]
我看了好像有eval_func()这个函数，但是一直没有用到

**Comment by heshuting555** [comment]
是滴呢，因为我当时跑的时候没有分验证集。直接线上提交的呢。

**Comment by hfyer** [comment]
在哪看到的eval_func()啊

**Comment by hfyer** [comment]
> 我看了好像有eval_func()这个函数，但是一直没有用到

在哪看到的eval_func()啊
