### ISSUE TITLE
请问大佬数据处理部分的‘normal'和’green'代表的是什么？

### ISSUE THREAD

**Issue by wangwl-tech** [heshuting555/NAIC_Person_ReID_DMT#8]

**Comment by heshuting555** [comment]
NAIC2019的数据包括红蓝图(normal)和绿图(green)呢

**Comment by nongkeyuandebaocai** [comment]
感谢。请问运行train_UDA.py时的model.load_parm(cfg_test.TEST.WEIGHT)中的cfg_test.TEST.WEIGHT是用的哪个呢？因为我不了解您的UDA用的是啥方法

**Comment by hfyer** [comment]
> NAIC2019的数据包括红蓝图(normal)和绿图(green)呢

初赛也需要划分红蓝图和绿图吗
